### ISSUE TITLE
badge proposal

### ISSUE THREAD

**Issue by steenzout** [funkybob/stencil#13]
On most of the repos I use on GitHub they have badges.

I can make a PR for the following services:

- https://travis-ci.org/
- https://landscape.io/
- https://coveralls.io/
- https://requires.io/
- https://www.openhub.net/p/python-stencil-template

let me know if you want this, all of them or just some.

cheers!

**Comment by funkybob** [comment]
Wow, cool... thanks!

Given there are no dependencies, is requires.io worth it?  Or do we need to subscribe for when we _are_ a dep?

Landscape seems interesting, but (a) requires an email even when you say don't email me, and (b) somehow can't get it from github info like everyone else.
Does not impress me.

Otherwise, bring it on!

I have to ask, are you using stencil for anything?

**Comment by steenzout** [comment]
true, requires.io wouldn't be necessary but it would be harmless if it was added (it would always be up2date).

I don't recall how I signed up for landscape (several years ago) but I typically login using my GitHub account.

not yet but I will be using.
I'm just getting more acquainted with what it does and how it does and making these minor contributions at the same time.
the fact you now have tests and builds on travis-ci means I'll probably start using it (I already have a personal project in mind where I could possibly replace Jinja2 or add this as an alternative).

**Comment by funkybob** [comment]
Cool.  Well, some simple benchmarks already show it's quite performant, so... :)

**Comment by ernstki** [comment]
Hello from the future! Those years go by quick!

Your README is neatly wrapped at 80-ish columns, readable in a text terminal and Notepad alike. 

I know there's a whole GitHub subculture that treats READMEs like GeoCities homepages—and that's fine! There's a tipping point at which the READMEs become _unreadable_, though. `;)`
